# Generated by Django 3.1.5 on 2021-02-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Marks', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
